name: automation
on:
  schedule:
    - cron: '30 */5 * * *'
  workflow_dispatch:

jobs:

  Initialization:
    runs-on: ubuntu-latest
    env:
      HOST_EMAIL: ${{ secrets.HOST_EMAIL }}
      HOST_EMAIL_PASSWORD: ${{ secrets.HOST_EMAIL_PASSWORD }}
      TOKEN: ${{ secrets.TOKEN }}

    steps:

      - name: Install Dependencies
        run: sudo pip install gspread

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          repository: kitsunejasutin/UDM_Admission_Automation
          token: ${{ secrets.TOKEN }}
          ref: main

      - name: Copy out Service Account
        run: sudo mkdir ~/.config/gspread/ && sudo mv service_account.json ~/.config/gspread/service_account.json

      - name: Work
        run: python3 app.py ${{ secrets.HOST_EMAIL }} ${{ secrets.HOST_EMAIL_PASSWORD }}
